n2 = float(input('Digite a nota: ').replace(',','.'))
n3 = float(input('Digite a nota: ').replace(',','.'))
n4 = float(input('Digite a nota: ').replace(',','.'))
n1 = float(input('Digite a nota: ').replace(',','.'))
print(f'Sua media é: {round((n1+n2+n3+n4)/4, 2)}')